#!/usr/bin/env node
/*
 * Builds ringfence/index.html as ONE self-contained file by inlining the
 * stylesheet and scripts referenced from src/index.html.
 *
 *   node ringfence/tools/build.js          # write index.html
 *   node ringfence/tools/build.js --check  # exit 1 if index.html is stale
 *
 * Why: a page that loads css/ and js/ from sibling files renders black and
 * white (or blank) anywhere that only fetches the HTML file itself, such as
 * file previews, attachments or a single downloaded file. Edit src/, css/
 * and js/, then rebuild. Don't edit index.html by hand.
 */
'use strict';
const fs = require('fs');
const path = require('path');

const root = path.join(__dirname, '..');
const srcDir = path.join(root, 'src');
const out = path.join(root, 'index.html');

function read(rel) {
  const text = fs.readFileSync(path.join(srcDir, rel), 'utf8');
  if (/<\/(script|style)/i.test(text)) throw new Error(rel + ' contains a closing script/style tag; it cannot be inlined.');
  return text.replace(/\s+$/, '');
}

let html = fs.readFileSync(path.join(srcDir, 'index.html'), 'utf8');
let inlined = 0;
// Replacer functions, not strings: the sources contain `$`, which string
// replacements would treat as special patterns.
html = html.replace(/<link rel="stylesheet" href="([^"]+)" \/>/g, (_, href) => {
  inlined++;
  return '<style>\n/* ' + path.posix.basename(href) + ' */\n' + read(href) + '\n</style>';
});
html = html.replace(/<script src="([^"]+)"><\/script>/g, (_, src) => {
  inlined++;
  return '<script>\n/* ' + path.posix.basename(src) + ' */\n' + read(src) + '\n</script>';
});
if (inlined < 4) throw new Error('Expected to inline a stylesheet and the scripts, inlined only ' + inlined + '.');
html = html.replace('<html lang="en">', '<html lang="en">\n<!-- GENERATED by ringfence/tools/build.js from src/index.html, css/ and js/. Do not edit by hand. -->');

if (process.argv.includes('--check')) {
  const current = fs.existsSync(out) ? fs.readFileSync(out, 'utf8') : '';
  if (current !== html) {
    console.error('ringfence/index.html is out of date. Run: node ringfence/tools/build.js');
    process.exit(1);
  }
  console.log('ringfence/index.html is up to date.');
} else {
  fs.writeFileSync(out, html);
  console.log('Wrote ' + path.relative(process.cwd(), out) + ' (' + Math.round(html.length / 1024) + ' KB, self-contained).');
}
